FROM python:3.12-alpine

WORKDIR /apps

COPY requirements.txt .

RUN apk update && \
    pip install -r requirements.txt

COPY app.py .

EXPOSE 5000

CMD [ "flask", "--app", "app.py", "run", "--host=0.0.0.0", "--port", "5000" ]
